#!/bin/bash
# Export database schema + config rows (with secrets purged) to schema.sql
# Run this every time the schema changes.

DB="${1:-leads.db}"
OUT="schema.sql"

{
    echo "-- Schema export: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "-- Generated by export_schema.sh — do not edit manually"
    echo ""

    # Dump schema (CREATE TABLE/INDEX statements)
    sqlite3 "$DB" ".schema"

    echo ""
    echo "-- Config seed values (secrets purged)"

    # Use Python to safely export config rows (handles JSON blobs, pipes, etc.)
    python3 -c "
import sqlite3, sys
con = sqlite3.connect('$DB')
rows = con.execute('SELECT name, value FROM config ORDER BY name').fetchall()
secrets = ('password', 'api_key', 'system_key', 'cookies')
for name, value in rows:
    if any(s in name for s in secrets):
        value = '**REDACTED**'
    escaped = value.replace(\"'\", \"''\") if value else ''
    print(f\"INSERT OR IGNORE INTO config (name, value) VALUES ('{name}', '{escaped}');\")
con.close()
"
} > "$OUT"

echo "Exported schema to $OUT"
