-- Schema export: 2026-03-12T19:20:28Z
-- Generated by export_schema.sh — do not edit manually

CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE sync_meta (
            key   TEXT PRIMARY KEY,
            value TEXT
        );
CREATE TABLE eventective_leads (
        -- PK
        EventId                 TEXT PRIMARY KEY,

        -- Inbox metadata (from leads)
        RequestGuid             TEXT,
        RequestProviderNum      INTEGER,
        ProviderNum             INTEGER,
        ProviderName            TEXT,
        EmailSentDttm           TEXT,
        IsFlagged               INTEGER,
        PurchasedLead           INTEGER,
        DirectLead              INTEGER,
        EventDate               TEXT,
        AttendeeCount           INTEGER,
        PlannerName             TEXT,
        PlannerStatusCd         TEXT,
        LastActivityDttm        TEXT,
        LastActivity            TEXT,
        LastActivityType        TEXT,
        LastActivityIsAutoResponse INTEGER,
        LastActivitySender      TEXT,
        AvatarMediaNum          INTEGER,
        IsRead                  INTEGER,
        UnreadCount             INTEGER,
        LeadStatus              TEXT,
        IsAvailable             INTEGER,
        DateAvailableType       TEXT,
        EventType               TEXT,
        EventNum                INTEGER,
        GmtOffsetHours          REAL,
        Source                  TEXT,
        DetailScrapedAt         TEXT,

        -- Detail fields (from lead_details)
        ProviderNameFull        TEXT,
        ProviderEmailGeneric    TEXT,
        RequestorName           TEXT,
        RequestorEmailAddress   TEXT,
        RequestorPhone          TEXT,
        RequestorContactPref    TEXT,
        EventName               TEXT,
        DatePossible1           TEXT,
        DateAvailable           INTEGER,
        DateFlexible            INTEGER,
        Duration                TEXT,
        TimePossible1           TEXT,
        BudgetValue             REAL,
        DirectLeadLocation      TEXT,
        InformationRequested    TEXT,
        ServicesRequested       TEXT,
        FoodRequired            INTEGER,
        VenueProvidesFood       INTEGER,
        CatererProvidesFood     INTEGER,
        SelfProvidesFood        INTEGER,
        IsEmailReguser          INTEGER,
        PhoneViewed             INTEGER,
        PhoneViewedDttm         TEXT,
        EmailViewed             INTEGER,
        EmailViewedDttm         TEXT,
        ConfirmReceivedDttm     TEXT,
        IsStripeEnabled         INTEGER,
        IsSquareEnabled         INTEGER,
        ScrapedAt               TEXT,

        -- FUB tracking
        fub_exported            INTEGER DEFAULT 0,
        fub_exported_date       TEXT,
        fub_people_id           TEXT
    );
CREATE INDEX idx_el_lastactivity ON eventective_leads(LastActivityDttm);
CREATE INDEX idx_el_fub_exported ON eventective_leads(fub_exported);
CREATE TABLE eventective_lead_activities (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        EventId             TEXT NOT NULL,
        DateTime            TEXT,
        DateTimeLong        TEXT,
        ActivityTypeCd      TEXT,
        Sender              TEXT,
        Recipient           TEXT,
        ResponseText        TEXT,
        IsRead              INTEGER,
        ResponseNum         INTEGER,
        HasAttachments      INTEGER,
        IsAutoResponse      INTEGER,
        EventDocumentNum    INTEGER,
        EventPaymentNum     INTEGER,
        PaymentAmount       REAL,
        ReguserNum          INTEGER,
        ActionNum           INTEGER,

        -- FUB tracking
        fub_exported            INTEGER DEFAULT 0,
        fub_exported_date       TEXT,
        fub_people_id           TEXT,

        UNIQUE(EventId, DateTime, ActivityTypeCd, ResponseNum)
    );
CREATE INDEX idx_ela_eventid ON eventective_lead_activities(EventId);
CREATE INDEX idx_ela_fub_exported ON eventective_lead_activities(fub_exported);
CREATE TABLE config (name TEXT PRIMARY KEY, value TEXT);

-- Config seed values (secrets purged)
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_batch_size', '20');
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_cookies', '**REDACTED**');
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_email', 'info@rentyellowhammer.com');
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_inbox_url', 'https://www.eventective.com/myeventective/#/crm/Event/Inbox');
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_password', '**REDACTED**');
INSERT OR IGNORE INTO config (name, value) VALUES ('eventective_signin_url', 'https://www.eventective.com/signin');
INSERT OR IGNORE INTO config (name, value) VALUES ('fub_api_base_url', 'https://api.followupboss.com/v1');
INSERT OR IGNORE INTO config (name, value) VALUES ('fub_api_key', '**REDACTED**');
INSERT OR IGNORE INTO config (name, value) VALUES ('fub_system_header', 'IRBY-GROUP-FUB-API');
INSERT OR IGNORE INTO config (name, value) VALUES ('fub_system_key', '**REDACTED**');
INSERT OR IGNORE INTO config (name, value) VALUES ('sync_batch_size', '100');
INSERT OR IGNORE INTO config (name, value) VALUES ('sync_rate_limit_seconds', '1.5');
